### ISSUE TITLE
Exception not logged to Database/File

### ISSUE THREAD

**Issue by Nitin2706** [ElmahCore/ElmahCore#10]
Used ElmahCore in my asp.net core 2.1 web api project but exception is not logged to DB or Path
Below is the code

public void ConfigureServices(IServiceCollection services)
        {
            services.AddElmah(options => options.Path = @"C:\");
            services.AddElmah<SqlErrorLog>(options => options.ConnectionString = ConnectionString);
            services.AddMvc().SetCompatibilityVersion(CompatibilityVersion.Version_2_1);
            services.AddCors(options =>
            {
                options.AddPolicy("CorsPolicy",
                    builder => builder.AllowAnyHeader()
                        .AllowAnyMethod()
                        .AllowAnyOrigin()
                        .AllowCredentials()
                );
            });
            services.AddAuthentication(IISDefaults.AuthenticationScheme);
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IHostingEnvironment env)
        {
            app.UseElmah();
            app.UseCors("CorsPolicy");
            if (env.IsDevelopment())
                app.UseDeveloperExceptionPage();
            else
                app.UseHsts();

            app.UseHttpsRedirection();

            app.UseMvc();
        }

**Comment by ElmahCore** [comment]
1) in ConfigureServices(IServiceCollection services)
```cs
services.AddElmah<SqlErrorLog>(options =>
{
    options.ConnectionString = "connection_string"; 
});
```
...
2) in Configure()
```cs
  app.UseElmah()

```

**Comment by iHamzaKhanzada** [comment]
SqlErrorLog is not found while adding it to ConfigureServices method in Startup.cs

**Comment by iHamzaKhanzada** [comment]
> SqlErrorLog is not found while adding it to ConfigureServices method in Startup.cs

I had to install ElmahCore.Sql nuget package for this

**Comment by lynhrom** [comment]
Hi everyone,

Could I change default table named ELMAH_Error to another one?
