### ISSUE TITLE
Elmah 'Data loading error' when recorded entries contain invalid characters in XML

### ISSUE THREAD

**Issue by conficient** [ElmahCore/ElmahCore#101]
Our ElmahCore installation stopped returning errors and showed the error `Data loading error`. The request to `/elmah/api/errors` returned 200 but with a blank response.

Investigating I found some requests logged to ELMAH where the request body was encoded as follows:
```xml
 <form>
    <item
      name="$request-body">
      <value string="&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;" />
    </item>
  </form>
 ```
The character `&#x0;` is not a valid XML character encoding. This causes an exception in `ErrorXml.UpcodeTo` at [line 415](https://github.com/ElmahCore/ElmahCore/blob/9bc011837db36b9892f34f1327f7c337f20584e3/ElmahCore/ErrorXml.cs#L415) when the reader tries to read the `value` element.

### Cause

I traced the code for where the `ErrorXml` serializes to XML, and [find this](https://github.com/ElmahCore/ElmahCore/blob/9bc011837db36b9892f34f1327f7c337f20584e3/ElmahCore/ErrorXml.cs#L181):
```c#
            using var writer = XmlWriter.Create(sw, new XmlWriterSettings
            {
                Indent = true,
                NewLineOnAttributes = true,
                CheckCharacters = false,
                OmitXmlDeclaration = true // see issue #120: http://code.google.com/p/elmah/issues/detail?id=120
            });
```
The `CheckCharacters = false` is allowing invalid characters to be serialized but isn't set when reading, hence the error.

I tested a fix locally by added `XmlReaderSettings` to the `Decode` like this and it worked:
```c#
            using (var reader = XmlReader.Create(sr, new XmlReaderSettings() { CheckCharacters = false }))
```
This mirrors the method of serialization to prevent these errors.

**Comment by MiroslavGrozdanovski** [comment]
@ElmahCore, can we publish this fix to Nuget?

I'm having the same issue and I've confirmed that this change fixes the issue by downloading the DemoCore3 project and pointing it to our database. That way I noticed that the version of the ElmahCore project is 2.0.7, and the latest on Nuget is 2.0.6.

I see that the missing font issues were also fixed, so I guess you will bump the ElmahCore.Mvc project as well.

Thanks!

**Comment by MLWakeman** [comment]
> @ElmahCore, can we publish this fix to Nuget?
> 
> I'm having the same issue and I've confirmed that this change fixes the issue by downloading the DemoCore3 project and pointing it to our database. That way I noticed that the version of the ElmahCore project is 2.0.7, and the latest on Nuget is 2.0.6.
> 
> I see that the missing font issues were also fixed, so I guess you will bump the ElmahCore.Mvc project as well.
> 
> Thanks!

@ElmahCore  - Agree is this close to a new release? We are encountering this issue as well. Would prefer to stick to a released nuget

**Comment by yeganehaym** [comment]
same for me

**Comment by andreluizsecco** [comment]
Any news about the new release in the Nuget package? I have the same problem.

**Comment by yeganehaym** [comment]
it seems this project is not under maintenance anymore

**Comment by afastrunner** [comment]
He went dark for months last time then came back and merged a bunch of stuff pushed out a few versions and launched the whole new error log interface.  I don't think it's dead but I also wish we got a bit more interaction.
