### ISSUE TITLE
RiseError method does not work when called as an extension method

### ISSUE THREAD

**Issue by MiroslavGrozdanovski** [ElmahCore/ElmahCore#103]
Calling `httpContext.RiseError(new Exception())` does not work (it does nothing). It worked in previous versions, and it's still a public API, so that's why I'm reporting this as a bug, even though there is an alternative of directly calling `ElmahExtensions.RiseError(new Exception())`.

After digging into the code, this is caused because the `ErrorLogMiddleware` class is no longer registered with DI. This bug should either be fixed or this public API should be removed, as without downloading the repo and debugging through the Demo projects, it's very difficult to figure out why it's silently failing.

**Comment by vssaini** [comment]
Yes! And here I spend almost the day finding out what I'm doing wrong.

**Comment by User00015** [comment]
Just ran into this issue as well. Thanks for posting it; I couldn't figure out why Elmah suddenly stopped working in my project.

**Comment by MohsenZeinaly** [comment]
try this code in controller

ElmahExtensions.RiseError(new Exception("your msg"));
