### ISSUE TITLE
Infinite loop in new-errors API endpoint.

### ISSUE THREAD

**Issue by cheese83** [ElmahCore/ElmahCore#108]
In [`ErrorLog.GetNewErrorsAsync`](https://github.com/ElmahCore/ElmahCore/blob/3c17817eb894e1d4897b90483c43ea16070182e2/ElmahCore/Logs%24/ErrorLog.cs#L213), `page` is never incremented, so if the requested `id` is not in the first 10 errors, it will keep reading the same page over and over until it runs out of memory.

**Comment by followynne** [comment]
Hi @cheese83,
I made a PR to fix this issue. Do you mind give it a look, to give it a like if it fixes your issue? :)
