### ISSUE TITLE
Error when accessing Request.Form

### ISSUE THREAD

**Issue by jrsearles** [ElmahCore/ElmahCore#11]
I am running into an issue when logging some errors into Elmah. I tracked it down to the access to `Request.Form` which is throwing an InvalidOperationException inside of the `Error` constructor. This appears to happen when there is no body - for example with AJAX JSON requests. I believe the [HasFormContentType](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.http.httprequest.hasformcontenttype?view=aspnetcore-2.1) property should be checked before accessing the Form property.

https://github.com/ElmahCore/ElmahCore/blob/7319554d8d39817223eb8bb9d041d6109b9354f7/ElmahCore/Error.cs#L119

**Comment by ElmahCore** [comment]
Closed in 1.2.1
