### ISSUE TITLE
[Feature Request] - Increase Message size up from 500 to max?

### ISSUE THREAD

**Issue by jafin** [ElmahCore/ElmahCore#119]
Is there any restriction that keeps the database column for `Message` limited at `nvarchar(500)`,  can it be bumped to `nvarchar(max)`?

At a bare minimum it would be preferrable if ElmahCore did not throw an exception (MSSQL) when the Message value is > 500.   Perhaps if not able to expand column then truncate text beyond the limit to at least ensure a valid exception is logged (if store is DB).

Happy to do a PR if there are no issues.

**Comment by Jacques-eMediaIT** [comment]
I think the limit is on the SQL side - try updating the column from 500 to max and see if the error still happens?

**Comment by jafin** [comment]
@Jacques-eMediaIT thank you, this is not an error. This is a request to adjust the default to not be 500.  I could not see a reason to keep the value at 500 for this field.

For an existing install, a migration or update script would need to be provided to avoid causing problems for anyone who updated to a version with the increased limit.
