### ISSUE TITLE
API Startup crash due to SQL server unavailable.

### ISSUE THREAD

**Issue by MrJacquers** [ElmahCore/ElmahCore#120]
If the SQL server is unavailable my .Net Core API crashes at startup. While this is obviously an issue for the API functioning, I don't think it should make it crash at startup.

```
services.AddElmah<SqlErrorLog>(options =>
            {
                options.ApplicationName = "My App Name";
                options.ConnectionString = _configuration.GetSection("ConnectionStrings")["MyConnection"];                
            });
```

**Comment by Jacques-eMediaIT** [comment]
Tracked it down to the CreateTableIfNotExists method. Please put it in a try catch :)

**Comment by nathangreaves-xplor** [comment]
@ElmahCore 
cc: @jafin 
Please could we have a NuGet release with this fix in?
