### ISSUE TITLE
AllXML Size Issue - Sqllog being appened

### ISSUE THREAD

**Issue by MrJacquers** [ElmahCore/ElmahCore#126]
I'm having an issue with the MS SQL Elmah_Error Table growing massively.

I've tracked it down to the AllXML column. Specifically it seems like each error that is logged also logs the previous one's sql command in the sqllog element. So the more errors you log the bigger the list and resulting entries get. I'm using ElmahExtensions.RiseError()

Example attached:

[Debug.zip](https://github.com/ElmahCore/ElmahCore/files/7382605/Debug.zip)

**Comment by ElmahCore** [comment]
#141
