### ISSUE TITLE
stylesheet 404 when there is url path

### ISSUE THREAD

**Issue by wickyhu** [ElmahCore/ElmahCore#13]
Hi, 

I found an issue about stylesheet, it seems related to issue #3 but not yet fixed.

To re-produce the issue: 
1. Get the latest source from git
2. Add app.UsePathBase("/test"); to beginning of ElmahCore.Demo->Startup->Configure
3. run and visit http://localhost:5000/test/el/mah 
4. you can see stylesheet lost with 404 error, the wrong url is  https://localhost:5001/test/test/el/mah/stylesheet?h=...
the correct one should be  https://localhost:5001/test/el/mah/stylesheet?h=...

Best Regards
Wicky

**Comment by wickyhu** [comment]
Hi,

As tested, it seems the issue caused by below line in About/ErrorLog/ErrorDetail pages:

Layout = new MasterPage.MasterPage {
...
   ElmahRoot = ElmahRoot;
...
}

ElmahRoot definition is:  
public string ElmahRoot
{
		    get => Request.PathBase + _elmahRoot;
		    set => _elmahRoot = value;
}

I think it should pass value of _elmahRoot  to  MasterPage but not Request.PathBase + _elmahRoot.

Best Regards
Wicky

**Comment by FruitAndAShape** [comment]
This happens when elmah is running in a virtual directory. Also, every request to see the errors results in a new 404 error due to the missing style sheet.

**Comment by barestan** [comment]
1) Add app.UseElmah before  app.UsePathBase("/test");
2) Set full path in elmah options:
	        services.AddElmah(options =>
	        {
	            options.Path = "test/el/mah";
	        });

**Comment by iStelmuhov** [comment]
I don't use app.UsePathBase("/test");
But I run app on LocaIIS, and it don't work for me.
