### ISSUE TITLE
Obtain the error Id

### ISSUE THREAD

**Issue by freerider75** [ElmahCore/ElmahCore#131]
Hi, 
With the "classic asp.net" Elmah I could write a global exception handler to obtain the generated log id and put it into a response header, or display it in a custom error page.
Now the code is too closed and this became impossible - my problem is that I really need access to the new error id.

My proposal is either one of the following:
1. Change the IErrorNotifier.Notify method signature in order to include the id as a parameter;
2. Allow to subscribe the ErrorLogMiddleware.Logged event (through a new ElmahOptions delegate?);

What do you think / any other suggestions?

thank you,
cheers!

**Comment by ElmahCore** [comment]
Use IErrorNotifierWithId
see #131
