### ISSUE TITLE
elmahcore not work correctly in asp.net core 6.0.1

### ISSUE THREAD

**Issue by amir3321** [ElmahCore/ElmahCore#133]
I use your app in asp.net core . elmahcore work in asp.net core 3.1 .but after upgrade to .net 6 not work correctly and only log error 404 
please check it.
Thank you very much.

**Comment by ElmahCore** [comment]
Not confirmed.
See ElmahCore.DemoCore6 project.

**Comment by inkersolution** [comment]
> I use your app in asp.net core . elmahcore work in asp.net core 3.1 .but after upgrade to .net 6 not work correctly and only log error 404 please check it. Thank you very much.

By installing ELMAHCode - all CSHTML pages stopped working.
