### ISSUE TITLE
Inconsistent property SendYsod in EmailOptions

### ISSUE THREAD

**Issue by wickyhu** [ElmahCore/ElmahCore#14]
Hi,

I happened to find while browsing, the SendYsod in EmailOptions is assigned to NoYsod internally:

ElmahCore\ElmahCore.Mvc\Notifiers\ErrorMailNotifier.cs:
_noYsod = options.SendYsod;

protected bool NoYsod
        {
            get { return _noYsod; }
        }

I guess the meaning of the property is just reversed.

Best Regards
Wicky

**Comment by ElmahCore** [comment]
Closed in 1.2.1
