### ISSUE TITLE
Can't read XML error files with encoded nulls

### ISSUE THREAD

**Issue by cheese83** [ElmahCore/ElmahCore#143]
The problem is that if an error is logged that contains a null character in the body, it's encoded and saved to the XML error file, but can't be read back again. It's easy to reproduce by adding an error file with the following contents...
```
<error errorId="2be61d3b-a1a9-4b76-9de3-133200ec8708">
  <form>
    <item name="$request-body">
      <value string="&#x0;" />
    </item>
  </form>
</error>
```
... and then trying to view it in the web interface, which will conplain about a "data loading error" because the API didn't return any of the logged errors.

This has actually been raised before with #101 and fixed by passing `CheckCharacters = false` to `XmlReader.Create`, however there are two more uses of `XmlReader.Create` that weren't fixed. They are at https://github.com/ElmahCore/ElmahCore/blob/1d045c0075dc760d831970a4c4066c9eb157e667/ElmahCore/Logs%24/XmlFileErrorLog.cs#L143 and https://github.com/ElmahCore/ElmahCore/blob/1d045c0075dc760d831970a4c4066c9eb157e667/ElmahCore/Logs%24/XmlFileErrorLog.cs#L183

**Comment by ElmahCore** [comment]
#143
