### ISSUE TITLE
Request body is logged inappropriately

### ISSUE THREAD

**Issue by cheese83** [ElmahCore/ElmahCore#144]
Request bodies are supposed to be logged conditionally depending on their content type, but the check for content type is broken and always passes. See https://github.com/ElmahCore/ElmahCore/blob/1d045c0075dc760d831970a4c4066c9eb157e667/ElmahCore.Mvc/ErrorLogMiddleware.cs#L162

This results in all sorts of weird characters being logged if for example the body is a file POSTed as `multipart/form-data`, which can then trigger #143.

**Comment by JonathanHopeDMRC** [comment]
When someone gets around to this also take a look at Transfer-Encoding: chunked. When that header is present the Content-Length header is not sent by well behaved HTTP clients. This results in the body stream with content being swapped out for an empty MemoryStream by ElmahCore. Given that the file is in the process of being streamed in this case; I don't think Elmah should try and log the request body when the Transfer-Encoding header is set to chunked.

**Comment by ElmahCore** [comment]
#144
