### ISSUE TITLE
log without context manually

### ISSUE THREAD

**Issue by npfernandeztheillet** [ElmahCore/ElmahCore#19]
In Elmah mvc version, you can log manually for example in projects without HttpContext.

I can't find a way to that.

**Comment by ElmahCore** [comment]
Use ElmahExtensions.RiseError (version 1.2.2)

**Comment by npfernandeztheillet** [comment]
Nice! thanks!

**Comment by xchan14** [comment]
It doesn't work on mine.

**Comment by janusund** [comment]
It doesn't work for me with .Net Core 3.0 and Elmah Core version 1.2.5 and Elmah Core Sql 1.2.5.
