### ISSUE TITLE
Style Sheet problem

### ISSUE THREAD

**Issue by npfernandeztheillet** [ElmahCore/ElmahCore#20]
On my app, i have the next url: http://localhost:port/myapi/

My elmah path is: /see/logs

When i try to open i use http://localhost:port/myapi/see/logs, it works but i have an error with the style sheets, it includes two times /myapi...i mean it look like: /myapi/myapi/see/logs.

Could you add some property to configure that or what i can do?

I'm using asp.netcore 2.2 with angularjs

_Originally posted by @npfernandeztheillet in https://github.com/ElmahCore/ElmahCore/issues/3#issuecomment-448629210_

**Comment by ElmahCore** [comment]
Release 1.2.3

**Comment by ericjankowski** [comment]
This issue may have regressed in release 1.2.5.  I am using .NET Core 3.0 and out of the box...
```
using ElmaCore.Mvc;

services.AddElmah();

app.UseElmah();
```

... the http://localhost:port/elmah page loads with expected content, but the stylesheet returned from the http://localhost:port/stylesheet?h=... request is empty.

Additionally, the ASP.NET Core Web Server log contains the following entry upon each request to http://localhost:port/elmah :

```
fail: ElmahCore.Mvc.ErrorLogMiddleware[0]
      Elmah request processing error
```

**Comment by sporifolous** [comment]
I'm experiencing the same issue.

**Comment by Joel-Paris** [comment]
I'm experiencing the same issue as well : the http://localhost:port/stylesheet?h=... request is empty.

**Comment by JasonRodman** [comment]
Any update on this? I am experiencing the same issue and none of the solutions I found have had any effect.

**Comment by matiaskusack** [comment]
Same here.

**Comment by guillaumejay** [comment]
I fixed it using https://github.com/ElmahCore/ElmahCore/issues/47#issuecomment-576855617

But I think we just need a new release, since I believe it's fixed in this https://github.com/ElmahCore/ElmahCore/commit/4d8f0ff810608acf7ea6730f85a4868e5a05fe3d

**Comment by vmandic** [comment]
Still reproing with Visual Studio / IIS on .NET Core 3.1

**Comment by mgarcos** [comment]
> Still reproing with Visual Studio / IIS on .NET Core 3.1

same

**Comment by carolinemilam** [comment]
Nuget Package 1.2.5 has same issue.  Please advise on work-around.

**Comment by guillaumejay** [comment]
It's fixed in 1.27, thanks !

**Comment by carolinemilam** [comment]
Thanks!

Caroline Milam

**Comment by npfernandeztheillet** [comment]
hey! good news!
