### ISSUE TITLE
Exception not logged when run application with Kestrel

### ISSUE THREAD

**Issue by lezhnevitransition** [ElmahCore/ElmahCore#24]
When I setup asp.net core project under my local IIS, exceptions are logged by the elmahcore. But when I run project from command line (with Kestrel only) using dotnet run command no exceptions logged, although the HttpContext.RiseError() is working well.
If I understand correctly it is because when I run with command line the application is started under development environment. And it looks that problem is in the order of the initialization of the exception handling middleware.
If it is initialized in this way: 
```csharp         
app.UseElmah();

if (env.IsDevelopment())
{
   app.UseDeveloperExceptionPage();
}
else
{
    app.UseExceptionHandler("/Home/Error");
    app.UseHsts();
}
```

The exceptions are not logged by the elmahcore in development environment.
But If it is initialized:
```csharp
if (env.IsDevelopment())
{
   app.UseDeveloperExceptionPage();
}
else
{
    app.UseExceptionHandler("/Home/Error");
    app.UseHsts();
}

app.UseElmah();
```
The exceptions are logged always.

So, I'd mention about this peculiarity in the documentation.

**Comment by ElmahCore** [comment]
Thank u, @lezhnevitransition. Documentation updated.
