### ISSUE TITLE
How to stop Mail triggering in Elmahcore when HttpStatusCode value is 401 UnAuthorized

### ISSUE THREAD

**Issue by sankarsudershan** [ElmahCore/ElmahCore#27]
Hi 
I am using Elmahcore for logging exceptions in .net core web api 2.2 application. 
In that i have done the settings for Mail Triggering in startup.cs file is 
services.AddElmah(options =>
            {

                options.Path = @"elmah";
                options.LogPath = "~/logs";               
                options.Notifiers.Add(new ErrorMailNotifier("Email", emailOptions));
            });
whenever i tried to hit the web api url i am getting the unauthorized exception through mail

i need to stop the mail triggering whenever there is UnAuthorized  exception came

please kindly help me out how to resolve this issue using filters.

**Comment by ElmahCore** [comment]
Try this
```csharp
services.AddElmah(options =>
{
            options.Path = @"elmah";
            options.LogPath = "~/logs";               
            options.Notifiers.Add(new ErrorMailNotifier("Email", emailOptions));
            options.Filters.Add(new DemoFilter());
});

...
 public class DemoFilter : IErrorFilter
    {
        private bool _dismissAll = false;
        public void OnErrorModuleFiltering(object sender, ExceptionFilterEventArgs args)
        {
            if (_dismissAll || args.Exception is UnauthorizedAccessException)
            {
                _dismissAll = true;
                args.DismissForNotifiers(new[] {"Email"});
            }
        }
    }
```

**Comment by sankarsudershan** [comment]
Thanks for reply..
i will try and let you know

**Comment by sankarsudershan** [comment]
Working fine!!!
Thanks.
