### ISSUE TITLE
How to user xml filter?

### ISSUE THREAD

**Issue by rafaeldruiz** [ElmahCore/ElmahCore#29]
I'm trying to use an elmah.xml with some filters, but it throws an exception of null reference.

Startup:
````
services.AddElmah<XmlFileErrorLog>(options =>
{
      options.FiltersConfig = "elmah.xml";
});
````

Xml filter:
````
<?xml version="1.0" encoding="utf-8" ?>
<elmah>
  <errorFilter>
    <test>
      <or>
        <!-- Filter 400 errors -->
        <equal binding="HttpStatusCode" value="400" type="Int32" />
        <!-- Filter 404 errors -->
        <equal binding="HttpStatusCode" value="404" type="Int32" />
      </or>
    </test>
  </errorFilter>
</elmah>
````

Error:
![image](https://user-images.githubusercontent.com/3640901/55106534-fd417300-50ad-11e9-8824-e5aa3bed4204.png)

If I remove the type XmlFileErrorLog, the filter does not work. 

Should I set the log directory to use the xml filter? What directory should I save the elmah.xml?

Thanks.

**Comment by ElmahCore** [comment]
Place file elmah.xml in the root of web project, 
or try this:
```chsharp
services.AddElmah(options =>
{
     options.FiltersConfig = @"full_path_to_xml\elmah.xml";
});

**Comment by rafaeldruiz** [comment]
I don't know why, but it started to work with:

```
services.AddElmah(options =>
{
     options.FiltersConfig = "elmah.xml";
});
```

Thanks for the help.
