### ISSUE TITLE
Page links & stylesheet not found when there is url path

### ISSUE THREAD

**Issue by Alexplose** [ElmahCore/ElmahCore#3]
ElmahCore is working well for app when url is like this : http://localhost/elmah
But when there is a path like : http://localhost/my.api/elmah

All resources are 404 because the path is not included.

I changed every :
    var basePageName = ElmahRoot;
to 
    var basePageName = Request.PathBase + ElmahRoot;

And it's working

Can you please add theses changes ?

**Comment by Alexplose** [comment]
Any way these changes ends in the nuget : https://www.nuget.org/packages/ElmahCore/

**Comment by funky81** [comment]
I dont think I can do that since I dont have the privilleges

**Comment by npfernandeztheillet** [comment]
Hi, i tried different things but doesn't work.
On my app, i have the next url: http://localhost:port/myapi/

I put path: /see/logs

when i try to open i use http://localhost:port/myapi/see/logs, it works but i have an error with the style sheets, it includes two times /myapi...i mean it look like: /myapi/myapi/see/logs.

Could you add some property to configure that or what i can do?

I'm using asp.netcore 2.2 with angularjs
