### ISSUE TITLE
CSS file not loading Core 3.0

### ISSUE THREAD

**Issue by ChaosSlave51** [ElmahCore/ElmahCore#47]
After upgrading my project to the release of Core 3.0 the css file no longer loads and just returns an empty page. 

I was able to reproduce this on the demo project in the repo just by upgrading it to core 3.0. I had to comment out 

```
     app.UseMvc(routes =>
            {
                routes.MapRoute(
                    name: "default",
                    template: "{controller=Home}/{action=Index}/{id?}");
            });
```

to run the project.

EDIT:
setting  o.ConfigureKestrel(options => options.AllowSynchronousIO = true); 
fixes the issue, but i am guessing is not a good solution

**Comment by gemon01** [comment]
also for me the same problem, it is not loaded the stylesheet! 
ho provato anche ad aggiungere:
_o.ConfigureKestrel(options => options.AllowSynchronousIO = true);_
ma niente ...!
[immagine](https://user-images.githubusercontent.com/56108523/66107250-0f9deb80-e5c0-11e9-93b9-c3586da8ad4a.png)

**Comment by keerthiraja1988** [comment]
To be more precises for 3.0, replace in Program.cs .

 public static IHostBuilder CreateHostBuilder(string[] args) =>
            Host.CreateDefaultBuilder(args)
             .UseServiceProviderFactory(new AutofacServiceProviderFactory())
                .ConfigureWebHostDefaults(webBuilder =>
                {
                    webBuilder.UseStartup<Startup>()
                     .ConfigureKestrel(options =>
                     {
                         options.AllowSynchronousIO = true;
                     });
                });

**Comment by gemon01** [comment]
![elmah](https://user-images.githubusercontent.com/56108523/67195474-49148a80-f3f9-11e9-9943-de68625f5a19.PNG)

same result! The style sheet is not loaded.

**Comment by wanderpaulo** [comment]
Hi!

Same problem! Any solution?

**Comment by faina09** [comment]
ref #48 

please merge!

**Comment by JonBraund** [comment]
I found this problem wasn't solved by the keerthiraja1988's code snippet when using IIS with the .net core 3 hosting bundle as kestrel doesn't seem to be relevant. Instead this similar snippet worked for me in ConfigureServices in startup.cs

`            services.Configure<IISServerOptions>(options =>
            {
                options.AllowSynchronousIO = true;
            });`

Hope this helps someone

**Comment by gemon01** [comment]
> 
> 
> I found this problem wasn't solved by the keerthiraja1988's code snippet when using IIS with the .net core 3 hosting bundle as kestrel doesn't seem to be relevant. Instead this similar snippet worked for me in ConfigureServices in startup.cs
> 
> ` services.Configure<IISServerOptions>(options => { options.AllowSynchronousIO = true; });`
> 
> Hope this helps someone

TOP !

**Comment by Luca7993** [comment]
another solution avoiding change the AllowSynchronousIO option is to intercept the stylesheet call and serve the static css file.

 in startup, in configure method use this (instead of simply app.UseElmah()):
` app.MapWhen(context => context.Request.Path.StartsWithSegments("/elmah", StringComparison.OrdinalIgnoreCase), appBuilder =>
            {
                appBuilder.UseMiddleware<MyMiddleware>();
                appBuilder.UseElmah();
            });`

MyMiddleware is this:
`public class MyMiddleware
        {
            private readonly RequestDelegate _next;

            public MyMiddleware(RequestDelegate next)
            {
                _next = next;
            }

            public async Task Invoke(HttpContext context)
            {
                if (context.Request.Path.HasValue && context.Request.Path.Value == @"/elmah/stylesheet")
                {
                    context.Response.Redirect("/css/elmah.min.css");
                }
                else
                {
                    // Call the next delegate/middleware in the pipeline
                    await _next(context);
                }
            }
        }`

where the path for redirect depend on where you put the static css file.
you can take the static css file using the two file Bootstrap.css and ErrorLog.css that you can find in this repository in ElmahCore/ElmahCore.mvc

**Comment by NickBranstein** [comment]
I had this same issue when using IIS so I do not think it is fully fixed. Instead of turning on SyncIO for the entire server you can combine the two above solutions and turn it off for specific requests.

```
app.UseWhen(context => context.Request.Path.StartsWithSegments("/elmah", StringComparison.OrdinalIgnoreCase), appBuilder =>
            {
                appBuilder.Use(next =>
                {
                    return async ctx =>
                    {
                        ctx.Features.Get<IHttpBodyControlFeature>().AllowSynchronousIO = true;

                        await next(ctx);
                    };
                });
            });

            app.UseElmah();
```
