### ISSUE TITLE
SQL not working with .Net Core 3.0 : Value cannot be null. (Parameter 'connectionString')

### ISSUE THREAD

**Issue by vlaine** [ElmahCore/ElmahCore#64]
Elmah is working properly with .net Core 3.0 until I activate SQL logging.
When I switch from "services.AddElmah(" to "services.AddElmah<SqlErrorLog>(" I receive the following error even after configuring the connection string

> •	System.ArgumentNullException: Value cannot be null. (Parameter 'connectionString')
> •	   at ElmahCore.Sql.SqlErrorLog..ctor(String connectionString)
> •	   at ElmahCore.Sql.SqlErrorLog..ctor(IOptions`1 option)
> •	--- End of stack trace from previous location where exception was thrown ---
> •	   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
> •	   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
> •	   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
> •	   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
> •	   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
> •	   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
> •	   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
> •	   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
> •	   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
> •	   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
> •	   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
> •	   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass1_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
> •	   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
> •	   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
> •	   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
> •	   at ElmahCore.Mvc.BuilderHelper.<>c.<<UseElmah>b__0_0>d.MoveNext()
> •	--- End of stack trace from previous location where exception was thrown ---
> •	   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
> •	   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
>    at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
> 

### Here's how I configured Elmah

**In ConfigureServices**
`var options = Configuration.GetSection("Elmah").Get<ElmahOptions>();
            EmailOptions emailOptions = new EmailOptions
            {
                SmtpServer = options.Host,
                MailSender = options.From,
                MailRecipient = options.To,
                MailSubjectFormat = $"Elmah - {options.ApplicationName} {options.Environnement} - Error ({{1}}): {{0}}"
            };

            services.AddElmah<SqlErrorLog>(options =>
            {
                options.ConnectionString = options.ConnectionString;
                options.ApplicationName = options.ApplicationName;
                options.Notifiers.Add(new ErrorMailNotifier("Email", emailOptions));
            });`

**In Configure**
`app.UseElmah();`

### Workaround
Replace "services.AddElmah<SqlErrorLog>(" by "services.AddElmah("­.  It disables SQL logging but the error is successfully sent by email.

### ElmahCore.Sql v1.2.5

**Comment by mb16** [comment]
I'm experiencing this issue with a .net core 3.1 project.  Any update on a fix?

**Comment by RobinGitHub** [comment]
How do you fixed it?

**Comment by yegorandrosov** [comment]
`var options = Configuration.GetSection("Elmah").Get();` is hidden by redeclaring variable in lambda signature, so the line below is doing nothing:
`options.ConnectionString = options.ConnectionString;`
rename your elmah options to something different, e.g. `elmahOptions`, so you can use
`configuration.ConnectionString = elmahOptions.ConnectionString`
