### ISSUE TITLE
.Net Core 3.0 - ElmahExtensions.RiseError not logging

### ISSUE THREAD

**Issue by vlaine** [ElmahCore/ElmahCore#65]
I am using ElmahExtensions.RiseError in my global error handler.   Since .net Core 3.0 it's not working anymore.  The call is made to RiseError, I do not get an exception, but nothing is logged and I don't receive the email.  If I remove the Global exception handler and throw an exception, Elmah sends the email correctly.

`public override void OnException(ExceptionContext context)
{
    ...
    ElmahExtensions.RiseError(context.Exception);
    base.OnException(context);
}`

I also tested ElmahExtensions.RiseError directly in my controller and I have the same issue.  Nothing is logged.

**Comment by puneetdevs** [comment]
try to use
HttpContext.RiseError(ex)

**Comment by janusund** [comment]
I am having the same issue. `HttpContext.RiseError(ex)` will only work if there is an HttpContext avaialable. ElmahCore  without HTTPContext `ElmahExtensions.RiseError` does not work.

**Comment by luciniga** [comment]
Any updates on this?

**Comment by AlexScigalszky** [comment]
On .Net Core 3.1, it not working

**Comment by MohsenZeinaly** [comment]
i can solve this problem with use ElmahExtensions class in my controller

ElmahExtensions.RiseError(new Exception("your msg"));
