### ISSUE TITLE
Since 2.0.* js and css files are 404 not found on server

### ISSUE THREAD

**Issue by jpmaistrebazin** [ElmahCore/ElmahCore#78]
I upgraded vesion from 1.2.7 to 2.0.2. In localhost no problem, but in release on my server hosted on IIS (windows server 2019), js and css are on http error 404 (not found)

![image](https://user-images.githubusercontent.com/26273151/103868940-e674e080-50c9-11eb-8ff0-b94184d5b39e.png)

Anyone can help me ?

**Comment by ElmahCore** [comment]
What happens if you make a request by IP?

**Comment by jpmaistrebazin** [comment]
If I make ra request by IP it's works !!
Why ?

**Comment by ElmahCore** [comment]
Looks like problems in IIS configuration.

**Comment by jpmaistrebazin** [comment]
Have you an idea ?

**Comment by ElmahCore** [comment]
Try the latest release (2.0.3)

**Comment by jpmaistrebazin** [comment]
Thks it's works !!
