### ISSUE TITLE
Accessing old Error class constructor

### ISSUE THREAD

**Issue by nehio** [ElmahCore/ElmahCore#87]
Hello,

I've update Elmah from 1.0.4 to 2.0.5 and i have the following piece of code that is not working anymore :

  
```
public void Log(Exception exception)
        {
            if (_environment.EnvironmentName.IsDevelopment())
            {
                return;
            }

            var connectionString = _configuration.GetConnectionString("Elmah");

            if (string.IsNullOrEmpty(connectionString))
            {
                return;
            }

            var sqlErrorLog = new MySqlErrorLog(connectionString);
            sqlErrorLog.Log(new Error(exception, _httpContext.HttpContext));
        }
```

The Log method expect an ElmahCore.Error class but when i looked at it the constructor was internal whereas the old constructor had a way to pass the arguments.

I saw in the code of ElmahCore that there's still a file Error2.cs with the old way of constructing error but i have not found a way to acces this error class.

**Comment by ElmahCore** [comment]
Try 2.0.6
